### ISSUE TITLE
The window position is wrong when there is a zoom ratio

### ISSUE THREAD

**Issue by xieerduos** [genesisneo/sokan#6]
Windows 10 is connected to the expansion screen, and the zoom ratio of screen 1 is changed to 125%. The specific settings are as follows: "Display Settings --> Scaling and Layout --> Change the size of items such as text and applications --> 125%".
The position of the extended screen display window is wrong

**Comment by genesisneo** [comment]
What is the position of your extended screen? Is it at the top, left, right, or bottom of your primary screen?

**Comment by xieerduos** [comment]
As long as the zoom ratio is set on the main screen, the position of the window is not correct regardless of whether it is placed on the top, bottom, left, or right.

I think that when there is a zoom ratio, the position returned by the const getWindowRect = user32.GetWindowRect(handle, rectPointer) method is incorrect, and it needs to be converted.

**Comment by xieerduos** [comment]
> What is the position of your extended screen? Is it at the top, left, right, or bottom of your primary screen?

As long as the zoom ratio is set on the main screen, the position of the window is not correct regardless of whether it is placed on the top, bottom, left, or right.

I think that when there is a zoom ratio, the position returned by the `const getWindowRect = user32.GetWindowRect(handle, rectPointer) `method is incorrect, and it needs to be converted.
